import localFont from 'next/font/local';
import { Nunito } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar/Navbar';
import Footer from './components/footer/Footer';
import Copyright from './components/copyright/Copyright';
import Categories from './components/categories/Categories';
import HomePagee from './components/frontpage/HomePagee';
import LoginModal from './components/modal/LoginModal';
import ReduxtoolkitProvider from '@/reduxtoolkit/ReduxtoolkitProvider';
import ListingCreationModal from './components/modal/listingcreationmodal/ListingCreationModal';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};
const font = Nunito({
	subsets: [ 'latin' ]
});
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={font.className}>
				<ReduxtoolkitProvider>
					<Navbar />
					{/* <Categories /> */}
					<LoginModal />
					<ListingCreationModal />
					{children}
					<Footer />
					<Copyright />
				</ReduxtoolkitProvider>
			</body>
		</html>
	);
}
